In [1]:
import torch
import torchvision
from torchvision import transforms, datasets
#https://pytorch.org/

In [18]:
import torch

#x = torch.Tensor([4,2])
#y = torch.Tensor([3,3])

z = [[[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]], [1,0]], [[[4,2,3,4,5],[8,7,8,9,10],[6,12,13,14,15]], [0,1]]]

x = []
y = []

X = torch.Tensor([i[0] for i in z])
Y = torch.Tensor([i[1] for i in z])
print(X)


tensor([[[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.],
         [11., 12., 13., 14., 15.]],

        [[ 4.,  2.,  3.,  4.,  5.],
         [ 8.,  7.,  8.,  9., 10.],
         [ 6., 12., 13., 14., 15.]]])


In [4]:
x = torch.zeros([2,5])
print(x)
x.shape
y = torch.rand([2,5])
print(y)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[0.3036, 0.6425, 0.6927, 0.0083, 0.6071],
        [0.9778, 0.0189, 0.2427, 0.2762, 0.0752]])


In [5]:
print(y.view([1,10]))
y = y.view([1, 10])

tensor([[0.3036, 0.6425, 0.6927, 0.0083, 0.6071, 0.9778, 0.0189, 0.2427, 0.2762,
         0.0752]])


In [9]:
x = torch.zeros([1,5])
x += 5
x.size()[1]

5

In [6]:
#creating the approximation of sin(x) as a third degree polynomial
import torch
import math

dtype = torch.float
device = torch.device("cpu")

#creates a tesnor with 2000 values between -pi and pi
x = torch.linspace(-math.pi, math.pi, 2000, device=device, dtype=dtype)
y = torch.sin(x)
#creates a tensor with the values of -pi to pi inputted into sin function

#genertaes 4 random numbers
a = torch.randn((), device=device, dtype=dtype)
b = torch.randn((), device=device, dtype=dtype)
c = torch.randn((), device=device, dtype=dtype)
d = torch.randn((), device=device, dtype=dtype)

learning_rate = 1e-6 #based off number of 'batches' and values in tensorspace 2k*2k
for t in range(2000):
    # creates a tensor of the predicted values from a,b,c,d values
    y_pred = a + b * x + c * x ** 2 + d * x ** 3
    # calculates how far y_pred was off from the actual value (SSE)
    loss = (y_pred - y).pow(2).sum().item()
    if t % 100 == 99:
        print(t, loss)
    
    #calculates gradient desent? for how far off each variable was 
    grad_y_pred = 2 * (y_pred - y)
    grad_a = grad_y_pred.sum()
    grad_b = (grad_y_pred * x).sum()
    grad_c = (grad_y_pred * x ** 2).sum()
    grad_d = (grad_y_pred * x ** 3).sum()

    #modifies variabes to get closer to minimize loss
    a -= learning_rate * grad_a
    b -= learning_rate * grad_b
    c -= learning_rate * grad_c
    d -= learning_rate * grad_d

print(f'rResult: y = {a.item()} + {b.item()} x + {c.item()} x^2 + {d.item()} x^3')

In [6]:
#creating the approximation of sin(x) as a third degree polynomial
import torch
import math

dtype = torch.float
device = torch.device("cpu")

#creates a tesnor with 2000 values between -pi and pi
x = torch.linspace(-math.pi, math.pi, 2000, device=device, dtype=dtype)
y = torch.sin(x)
#creates a tensor with the values of -pi to pi inputted into sin function

# Create random Tensors for weights. For a third order polynomial, we need
# 4 weights: y = a + b x + c x^2 + d x^3
# Setting requires_grad=True indicates that we want to compute gradients with
# respect to these Tensors during the backward pass.
a = torch.randn((), device=device, dtype=dtype, requires_grad=True)
b = torch.randn((), device=device, dtype=dtype, requires_grad=True)
c = torch.randn((), device=device, dtype=dtype, requires_grad=True)
d = torch.randn((), device=device, dtype=dtype, requires_grad=True)

learning_rate = 1e-6
for t in range(2000):
    # Forward pass: compute predicted y using operations on Tensors.
    y_pred = a + b * x + c * x ** 2 + d * x ** 3
    loss = (y_pred - y).pow(2).sum()
    if t % 100 == 99:
        print(t, loss.item())
    
    # Use autograd to compute the backward pass. This call will compute the
    # gradient of loss with respect to all Tensors with requires_grad=True.
    # After this call a.grad, b.grad. c.grad and d.grad will be Tensors holding
    # the gradient of the loss with respect to a, b, c, d respectively.
    loss.backward()

    # Manually update weights using gradient descent. Wrap in torch.no_grad()
    # because weights have requires_grad=True, but we don't need to track this
    # in autograd.
    with torch.no_grad():
        a -= learning_rate * a.grad
        b -= learning_rate * b.grad
        c -= learning_rate * c.grad
        d -= learning_rate * d.grad

        # Manually zero the gradients after updating weights
        a.grad = None
        b.grad = None
        c.grad = None
        d.grad = None

print(f'Result: y = {a.item()} + {b.item()} x + {c.item()} x^2 + {d.item()} x^3')

99 2171.65283203125
199 1441.50439453125
299 957.959228515625
399 637.6954345703125
499 425.5530700683594
599 285.0137023925781
699 191.89791870117188
799 130.19491577148438
899 89.301513671875
999 62.195377349853516
1099 44.225257873535156
1199 32.30982208251953
1299 24.4077091217041
1399 19.166011810302734
1499 15.688340187072754
1599 13.38056755065918
1699 11.84874153137207
1799 10.831730842590332
1899 10.156338691711426
1999 9.707670211791992
Result: y = -0.009218011982738972 + 0.8289952874183655 x + 0.0015902586746960878 x^2 + -0.0893838182091713 x^3


import torch
import torch.nn as nn
import torch.nn.functional as F

size = 10000
end_size = 5000

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(28*28, 512)
        self.fc2 = nn.Linear(512, 512)
        self.fc3 = nn.Linear(512, 512)
        self.fc4 = nn.Linear(512, end_size)

    def foward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        x = self.fc4(x)
        return F.log_softmax(x, dim=1)

net = Net()
print(net)

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, 3, 1) #takes in 1 image, outputs 32 convolutional features, swihta  square keranal size of 3
        self.conv2 = nn.Conv2d(32, 64, 3, 1) #takes in 32 input layers and outputs 64 features with a square keranl of 3

        self.dropout1 = nn.Dropout2d(0.25)
        self.dropout2 = nn.Dropout2d(.5)

        self.fc1 = nn.Linear(9216, 128)
        self.fc2 = nn.Linear(128, 10)

my_nn = Net()
print(my_nn)

Net(
  (conv1): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1))
  (dropout1): Dropout2d(p=0.25, inplace=False)
  (dropout2): Dropout2d(p=0.5, inplace=False)
  (fc1): Linear(in_features=9216, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=10, bias=True)
)


In [7]:
np.random.shuffle('somedata here')
np.save('adff.npy', 'data here')
#need tom implement some type of Conv1d on data

In [11]:
import torch
import torch.nn as nn
import torch.nn.functional as F

n = 1000

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        #we're gonna input a 3 column data set so n x 3 where n starts from 5? 10? 15? years ago when the stocks began? and then then if it began later subsitute zeros in.
        self.conv1 = nn.Conv2d(1, 64, 3)
        self.conv2 = nn.Conv2d(64, 128, 3)
        self.conv3 = nn.Conv2d(128, 256, 3)

        x = torch.randn(n, 3).view(-1, 1, n, 3)
        x = torch.flatten(x, 1)
        self._to_linear = x.size()[1]

        self.fc1 = nn.Linear(self._to_linear, 256)
        self.fc2 = nn.Linear(256, 128)
        self.fc3 = nn.Linear(128, 3)
    
    
    def foward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), 2)
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = F.max_pool2d(F.relu(self.conv3(x)), 2)
        x = torch.flatten(x, 1)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)

        return F.log_softmax(x, dim=1)

net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 64, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1))
  (conv3): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=3000, out_features=256, bias=True)
  (fc2): Linear(in_features=256, out_features=128, bias=True)
  (fc3): Linear(in_features=128, out_features=3, bias=True)
)


In [12]:
import torch.optim as optim

optmizer = optim.Adam(net.parameters(), lr=1e-3) #some use 1e-6
loss_function = nn.MSELoss()

# some data compiling thing where X is data and y is answer
# were going to have to store our data in a x * n * 3 tensor where x is number of stocks
#for the tesnor of 5/10 years. we gotta move it around so like some start at the v start, some v end, etc
# X stands for data
VAL_PCT = .25
val_size = int(len(X)*VAL_PCT)

train_X = X[:-val_size]
train_y = y[:-val_size]

test_X = X[-val_size:]
test_y = y[-val_size:]
print(len(train_X), len(test_X))


BATCH_SIZE = 50 #number of stocks we run each time
EPOCHS = 5 # how many times we run through the training data in general

for epoch in range(EPOCHS):
    for i in range(0, len(train_X), BATCH_SIZE):
        batch_X = train_X[i:i+BATCH_SIZE].view(-1, 1, n, 3)
        batch_y = train_y[i:i+BATCH_SIZE]

        net.zero_grad()

        outputs = net(batch_X)
        loss = loss_function(outputs, batch_y)
        loss.backward()
        optimizer.step()
    print(f"Epoch: {epoch}. Loss: {loss}")

NameError: name 'X' is not defined

In [13]:
correct = 0
total = 0
with torch.no_grad():
    for i in range(len(test_X)):
        real_class = torch.argmax(test_y[i])
        net_out = net(test_X[i].view(-1, 1, n, 3))[0]
        predicted_class = torch.argmax(net_out)

        if predicted_class == real_class:
            correct += 1
        total += 1
print("Accuracy: ", round(correct/total, 3))

NameError: name 'test_X' is not defined