In [1]:
import torch
import torchvision
from torchvision import transforms, datasets
#https://pytorch.org/

In [2]:
x = torch.Tensor([4,2])
y = torch.Tensor([3,3])
print(x*y)

tensor([12.,  6.])


In [3]:
x = torch.zeros([2,5])
print(x)
x.shape
y = torch.rand([2,5])
print(y)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[0.7204, 0.8427, 0.7856, 0.7274, 0.5595],
        [0.1468, 0.2587, 0.1926, 0.8775, 0.3617]])


In [4]:
print(y.view([1,10]))
y = y.view([1, 10])

tensor([[0.7204, 0.8427, 0.7856, 0.7274, 0.5595, 0.1468, 0.2587, 0.1926, 0.8775,
         0.3617]])


In [5]:
# you NEED to seperate out training and testing at the v start
train = datasets.MNIST("", train=True, download=True, transform=transforms.Compose([transforms.ToTensor()])) #have to make a custom method
test = datasets.MNIST("", train=False, download=True, transform=transforms.Compose([transforms.ToTensor()]))

  0%|          | 0/9912422 [00:00<?, ?it/s]Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to MNIST/raw/train-images-idx3-ubyte.gz
9920512it [00:00, 10217165.91it/s]                            
Extracting MNIST/raw/train-images-idx3-ubyte.gz to MNIST/raw
32768it [00:00, 231798.99it/s]           
0it [00:00, ?it/s]Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz to MNIST/raw/train-labels-idx1-ubyte.gz
Extracting MNIST/raw/train-labels-idx1-ubyte.gz to MNIST/raw
1654784it [00:00, 4898854.14it/s]                             
8192it [00:00, 66480.03it/s]            
Extracting MNIST/raw/t10k-images-idx3-ubyte.gz to MNIST/raw
Extracting MNIST/raw/t10k-labels-idx1-ubyte.gz to MNIST/raw
Processing...
Done!


In [6]:
trainset = torch.utils.data.DataLoader(train, batch_size=10, shuffle=True)
testset = torch.utils.data.DataLoader(test, batch_size=10, shuffle=True)

In [7]:
for data in trainset: 
    print(data)
    break

[tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        ...,


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0

In [8]:
x, y = data[0][0], data[1][0]

print(y)

tensor(1)


In [14]:
import matplotlib.pyplot as plt

#plt.imshow(data[0][0])
print(data[0][0].shape)

torch.Size([1, 28, 28])


In [29]:
#creating the approximation of sin(x) as a third degree polynomial
import torch
import math

dtype = torch.float
device = torch.device("cpu")

#creates a tesnor with 2000 values between -pi and pi
x = torch.linspace(-math.pi, math.pi, 2000, device=device, dtype=dtype)
y = torch.sin(x)
#creates a tensor with the values of -pi to pi inputted into sin function

#genertaes 4 random numbers
a = torch.randn((), device=device, dtype=dtype)
b = torch.randn((), device=device, dtype=dtype)
c = torch.randn((), device=device, dtype=dtype)
d = torch.randn((), device=device, dtype=dtype)

learning_rate = 1e-6 #based off number of 'batches' and values in tensorspace 2k*2k
for t in range(2000):
    # creates a tensor of the predicted values from a,b,c,d values
    y_pred = a + b * x + c * x ** 2 + d * x ** 3
    # calculates how far y_pred was off from the actual value (SSE)
    loss = (y_pred - y).pow(2).sum().item()
    if t % 100 == 99:
        print(t, loss)
    
    #calculates gradient desent? for how far off each variable was 
    grad_y_pred = 2 * (y_pred - y)
    grad_a = grad_y_pred.sum()
    grad_b = (grad_y_pred * x).sum()
    grad_c = (grad_y_pred * x ** 2).sum()
    grad_d = (grad_y_pred * x ** 3).sum()

    #modifies variabes to get closer to minimize loss
    a -= learning_rate * grad_a
    b -= learning_rate * grad_b
    c -= learning_rate * grad_c
    d -= learning_rate * grad_d

print(f'rResult: y = {a.item()} + {b.item()} x + {c.item()} x^2 + {d.item()} x^3')

99 805.6689453125
199 571.9332275390625
299 406.7931213378906
399 290.1056823730469
499 207.64674377441406
599 149.3707733154297
699 108.1820068359375
799 79.06796264648438
899 58.487403869628906
999 43.93802261352539
1099 33.651756286621094
1199 26.379009246826172
1299 21.23664093017578
1399 17.60041618347168
1499 15.029068946838379
1599 13.210663795471191
1699 11.924667358398438
1799 11.01516342163086
1899 10.371901512145996
1999 9.916925430297852
rResult: y = -0.034998469054698944 + 0.8542636036872864 x + 0.0060378205962479115 x^2 + -0.09297802299261093 x^3


In [30]:
#creating the approximation of sin(x) as a third degree polynomial
import torch
import math

dtype = torch.float
device = torch.device("cpu")

#creates a tesnor with 2000 values between -pi and pi
x = torch.linspace(-math.pi, math.pi, 2000, device=device, dtype=dtype)
y = torch.sin(x)
#creates a tensor with the values of -pi to pi inputted into sin function

# Create random Tensors for weights. For a third order polynomial, we need
# 4 weights: y = a + b x + c x^2 + d x^3
# Setting requires_grad=True indicates that we want to compute gradients with
# respect to these Tensors during the backward pass.
a = torch.randn((), device=device, dtype=dtype, requires_grad=True)
b = torch.randn((), device=device, dtype=dtype, requires_grad=True)
c = torch.randn((), device=device, dtype=dtype, requires_grad=True)
d = torch.randn((), device=device, dtype=dtype, requires_grad=True)

learning_rate = 1e-6
for t in range(2000):
    # Forward pass: compute predicted y using operations on Tensors.
    y_pred = a + b * x + c * x ** 2 + d * x ** 3
    loss = (y_pred - y).pow(2).sum()
    if t % 100 == 99:
        print(t, loss.item())
    
    # Use autograd to compute the backward pass. This call will compute the
    # gradient of loss with respect to all Tensors with requires_grad=True.
    # After this call a.grad, b.grad. c.grad and d.grad will be Tensors holding
    # the gradient of the loss with respect to a, b, c, d respectively.
    loss.backward()

    # Manually update weights using gradient descent. Wrap in torch.no_grad()
    # because weights have requires_grad=True, but we don't need to track this
    # in autograd.
    with torch.no_grad():
        a -= learning_rate * a.grad
        b -= learning_rate * b.grad
        c -= learning_rate * c.grad
        d -= learning_rate * d.grad

        # Manually zero the gradients after updating weights
        a.grad = None
        b.grad = None
        c.grad = None
        d.grad = None

print(f'Result: y = {a.item()} + {b.item()} x + {c.item()} x^2 + {d.item()} x^3')

99 66.88224792480469
199 49.77676773071289
299 37.71763610839844
399 29.212682723999023
499 23.213104248046875
599 18.98000717163086
699 15.9927396774292
799 13.884281158447266
899 12.395849227905273
999 11.344947814941406
1099 10.602865219116211
1199 10.078777313232422
1299 9.70859432220459
1399 9.447094917297363
1499 9.262346267700195
1599 9.131810188293457
1699 9.039566040039062
1799 8.974377632141113
1899 8.928304672241211
1999 8.89573860168457
Result: y = 0.009318584576249123 + 0.8557363152503967 x + -0.0016076096799224615 x^2 + -0.09318750351667404 x^3
